### ISSUE TITLE
It ignores http_proxy and https_proxy

### ISSUE THREAD

**Issue by redi-wadash** [verdaccio/verdaccio-audit#2]
We have setup like this:

```yml
https_proxy: http://address-of-proxy/

middlewares:
  audit:
    enabled: true
```

But it looks like audit doesn't use the proxy, hanging the request.

**Comment by juanpicado** [comment]
Oh, I did not try that. It needs a fix.

**Comment by redi-wadash** [comment]
I couldn't find a way for middleware to access main config. Is that possible? Or to support it, should the config become like this so that the middleware has access to it?

```yaml
middlewares:
  audit:
    enabled: true
    https_proxy: http://address-of-proxy/
```

I don't mind either way but am just curious how it should work.
